from .index import *
from .detail import *
from .machine_add import *
from .interface_add import *
from .interfaces_check import *
from .interfaces_stats import *
from .route_map_add import *
from .settings_set import *
from .login import *
from .logout import *
from .machine_del import *
from .blackhole import *
