# Generated by Django 2.0.2 on 2018-03-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=200)),
                ('snmp_number', models.IntegerField()),
                ('max_in', models.IntegerField()),
                ('max_out', models.IntegerField()),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('description', models.CharField(default='-', max_length=200)),
                ('community_name', models.CharField(default='pash', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_in', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Interfaces')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('net', models.GenericIPAddressField()),
                ('net_mask', models.IntegerField()),
                ('rm_seq', models.IntegerField()),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Machines')),
            ],
        ),
        migrations.CreateModel(
            name='RMtoPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.IntegerField()),
                ('prepend', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RouteMaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Machines')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.GenericIPAddressField()),
                ('net_mask', models.IntegerField()),
                ('max_prepend', models.IntegerField(default=5)),
                ('max_prefix', models.IntegerField(default=22)),
                ('nexthop', models.GenericIPAddressField(default='-')),
                ('m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Machines')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_in', models.IntegerField()),
                ('counter_out', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Interfaces')),
            ],
        ),
        migrations.AddField(
            model_name='rmtopl',
            name='rm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.RouteMaps'),
        ),
        migrations.AddField(
            model_name='neighbours',
            name='rm_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.RouteMaps'),
        ),
        migrations.AddField(
            model_name='interfaces',
            name='m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facer.Machines'),
        ),
        migrations.AlterUniqueTogether(
            name='settings',
            unique_together={('m', 'net')},
        ),
        migrations.AlterUniqueTogether(
            name='routemaps',
            unique_together={('m', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='prefixlists',
            unique_together={('m', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='interfaces',
            unique_together={('m', 'name')},
        ),
    ]
