# Generated by Django 2.0.2 on 2018-03-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0002_auto_20180314_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmtopl',
            name='pl_id',
        ),
    ]
