# Generated by Django 2.0.2 on 2018-03-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0003_remove_rmtopl_pl_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmtopl',
            name='pl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facer.PrefixLists'),
        ),
    ]
