# Generated by Django 2.0.2 on 2018-03-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0004_rmtopl_pl'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rmtopl',
            unique_together={('rm', 'pl')},
        ),
    ]
