# Generated by Django 2.0.2 on 2018-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0005_auto_20180314_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='login',
            field=models.CharField(default='pashorg', max_length=64),
        ),
        migrations.AddField(
            model_name='machines',
            name='password',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='machines',
            name='remote_as',
            field=models.IntegerField(default='65001', max_length=6),
        ),
        migrations.AddField(
            model_name='machines',
            name='ssh',
            field=models.BooleanField(default=True),
        ),
    ]
