# Generated by Django 2.0.2 on 2018-03-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0006_auto_20180315_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='enable_password',
            field=models.CharField(default='privet', max_length=64),
        ),
    ]
