# Generated by Django 2.0.2 on 2018-03-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0007_machines_enable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='quagga_seq',
            field=models.IntegerField(default=1),
        ),
    ]
