# Generated by Django 2.0.2 on 2018-03-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0009_remove_machines_ssh'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='rm_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='machines',
            name='remote_as',
            field=models.IntegerField(default='65001'),
        ),
    ]
