# Generated by Django 2.0.2 on 2018-03-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0010_auto_20180327_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='rm_id',
        ),
    ]
