# Generated by Django 2.0.2 on 2018-03-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0011_remove_interfaces_rm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='rm_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
