# Generated by Django 2.0.2 on 2018-03-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0012_interfaces_rm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='max_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interfaces',
            name='max_out',
            field=models.FloatField(),
        ),
    ]
