# Generated by Django 2.0.2 on 2018-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0013_auto_20180329_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='counter_in',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stats',
            name='counter_out',
            field=models.BigIntegerField(),
        ),
    ]
