# Generated by Django 2.0.2 on 2018-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0014_auto_20180412_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='nexthop',
            field=models.GenericIPAddressField(blank=True, default=None, null=True),
        ),
    ]
