# Generated by Django 2.0.2 on 2018-06-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0015_auto_20180416_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoNotDistribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='routemaps',
            name='community',
            field=models.BigIntegerField(default=0),
        ),
    ]
