# Generated by Django 2.0.2 on 2018-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facer', '0016_auto_20180613_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemaps',
            name='community',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
